services:
  - type: web
    name: ai_learning_bot
    env: python
    plan: free
    buildCommand: |
      echo "python-3.11.9" > runtime.txt
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
